version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
        environment:
            - discovery.type=single-node
            - cluster.name=elkdev
        ports:
            - "9200:9200"

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.0.0
        links:
            - elasticsearch
        ports:
            - "5601:5601"
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"
