version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
        environment:
            - discovery.type=single-node
            - cluster.name=elkdev

    logstash:
        image: docker.elastic.co/logstash/logstash-oss:6.0.0
        volumes:
            - ./logstash:/usr/share/logstash/config
        links:
            - elasticsearch
        ports:
            - "5044:5044"

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.0.0
        links:
            - elasticsearch
        ports:
            - "5601:5601"

