version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
        environment:
            - discovery.type=single-node
            - cluster.name=elkdev

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.0.0
        links:
            - elasticsearch
        ports:
            - "5601:5601"

